### ISSUE TITLE
CN_match deprecated in php 5.6.x

### ISSUE THREAD

**Issue by lucasgolino** [Dreyer/LightOpenID#2]
"the 'CN_match' SSL context option is deprecated in favor of 'peer_name'"

In update for 5.5.x => 5.6.x. I got this problem. :walking: 

PHP Report: http://php.net/manual/en/migration56.openssl.php

**Comment by lucasgolino** [comment]
Response for the problem: https://github.com/lucasgolino/LightOpenID/commit/aca202be482ee9631c633754bdc47be0a642c3de

**Comment by Dreyer** [comment]
Didn't spot this issue. Apologies.

I noticed that Gitorious has all but disappeared and with it the repository that this one mirrors:
https://gitorious.org/lightopenid

I found the reference you were referring to about the deprecation of `CN_match` in favour of `peer_name` as of PHP 5.6.0:
http://php.net/manual/en/context.ssl.php#context.ssl.cn-match

**Comment by Dreyer** [comment]
And it looks like the Archive Team are in the process of making a copy [?] of the old Gitorious website but who knows when they will be done/ready:
http://www.archiveteam.org/index.php?title=Gitorious
